### ISSUE TITLE
Soft lock, Substruction

### ISSUE THREAD

**Issue by Scarfman1** [RouterXdd/Erekir-Extended#12]
I m playing your mod (Nice btw) and i m on sector Substruction and k got soft locked on last Core (in descrip.) i reccomend solving this. Also i playbon mobile.

P.S.:Do i have to capture this sector to move on?

![Screenshot_20240927-145428](https://github.com/user-attachments/assets/3561b757-7135-4ead-98d0-e04287454128)

**Comment by RouterXdd** [comment]
I hope i fixed that...
