### ISSUE TITLE
'Fort' level impossible? 

### ISSUE THREAD

**Issue by joel4848** [RouterXdd/Erekir-Extended#14]
I've played this level maybe 10-15 times and each time I get absolutely demolished by the big tank that appears. Am I missing something? 

I've tried loads of things, but I simply can't get enough resources fast enough to build enough turrets to defend. It doesn't help that one of the first things that happens is the bomb going off thatddestroys some of the turrets you start with! 

I've tried all the turrets that I can build but none seem to even get close to damaging the tank (which appears to have some kind of shield? But piercing weapons don't seem to have much more effect). For example, at most I'm able to get enough tungsten to build two stronger turrets - but literally I managed to complete the second one as the tank spawned.

I don't think it's a skill issue. I've defeated every other area on Erekir, I've unlocked everything there is to unlock, I just can't seem to find anything that works at all on Fort.

**Comment by RouterXdd** [comment]
Ok, I quite made fort easier
But sector still can be undalanced

**Comment by joel4848** [comment]
> Ok, I quite made fort easier But sector still can be undalanced

Wow that was fast, that's really great thanks!

I can see on the code view here last updated 2 hours ago, but the latest 'release' is still 2022. Will the mod update properly if I go into the game (on my phone) and tap to reinstall the mod?

**Comment by joel4848** [comment]
@RouterXdd The mod has definitely updated, but the enemy tank is still impossible to kill. How do you do it successfully when you test the map?
