### ISSUE TITLE
Cores Trap Broken At 5-Minute Mark

### ISSUE THREAD

**Issue by Shadow-Diamond** [RouterXdd/Erekir-Extended#7]
Whenever I hit the 5-minute mark in Cores Trap it doesn't open up the rest of the map. Instead, it closes the center part of the map and constantly kills the player. 
Pictures of after the 5-Minute Mark:
(Without HUD)
![20230423162404_1](https://user-images.githubusercontent.com/58434079/233867074-ce5db72b-20e6-49cd-aaf0-516a637f6a79.jpg)
(With HUD)
![20230423162359_1](https://user-images.githubusercontent.com/58434079/233867166-863ce883-041b-4c18-b00b-246573d57a17.jpg)

**Comment by RouterXdd** [comment]
Now I fix this bug
Thank you for reporting
